### ISSUE TITLE
UnityEnvironmentException

### ISSUE THREAD

**Issue by vokhidovhusan** [yorkeyao/VehicleX#12]
@yorkeyao  I am getting following exception. I have try many hours to fix this issue, but couldn't figure out how to do it.
mlagents.envs.exception.UnityEnvironmentException: Couldn't launch the VehicleX environment. Provided filename does not match any environments

**Comment by regob** [comment]
I got the same error, the problem was that the env_path parameter was not passed to `train.py` in Linux (it defaults to the windows path): `--env_path "./Build-linux/VehicleX.x86_64"`
