### ISSUE TITLE
Use the unity-python

### ISSUE THREAD

**Issue by weilli** [yorkeyao/VehicleX#13]
Hello!
I want to use your 3D tool to generate some simple images, with various viewpoints, without background or light changes.
What should I do? Could you give me some advice?
Thanks very much!

**Comment by yorkeyao** [comment]
I think you can directly control these variables in https://github.com/yorkeyao/VehicleX/blob/master/VehicleX%20Interface/inference.py

**Comment by yorkeyao** [comment]
If you want to use your own 3D models, you may need to have a look at the source code of the Unity environment: 
https://github.com/yorkeyao/VehicleX/tree/master/Unity%20Source
