### ISSUE TITLE
can't access to the drive of backgroud images

### ISSUE THREAD

**Issue by yukichou** [yorkeyao/VehicleX#3]
https://drive.google.com/open?id=11JQMzaF7tUOEjZXzgVbFUTDjpgD_6wTr
404 error
could you send me the new access link to the background images
thank you~

**Comment by yorkeyao** [comment]
Thank you very much for let me know. I have updated the link. You can also check the link here: https://drive.google.com/file/d/1dx03ijDzJkbVp0XnZbvKLTYZSYMDJHsf/view?usp=sharing
