### ISSUE TITLE
some question about the database

### ISSUE THREAD

**Issue by ZYang2077** [yorkeyao/VehicleX#4]
thanks for sharing such excellent work, for the cityflow, how can i get the password for the password protected content?
and Is there a more detailed division of vehicle types rather than bus and truck? like BMW 2 series grand tour and Audi A2

**Comment by yorkeyao** [comment]
Thank you for your attention, you may need to sign up at ai city challenge 2020. Please check this link for more details: https://www.aicitychallenge.org/2020-evaluation-system/
We divide vehicle types into 11 classes. But sorry we do not have detailed labelling currently for different brands (but I think many vehicles can be branded).

**Comment by ZYang2077** [comment]
@yorkeyao thanks for your reply, i wonder if i can get the brands of the model in the unity source code? or can i manually branded the model in the unity source code? I want to get a dataset of vehicle models with specific brands instead of the current 11 classes, any suggestions?

**Comment by yorkeyao** [comment]
Yes, I think you can manually brand the model in the unity source. You may check with Attributes.cs for more details. Currently it just have vehicle color and vehicle type. You may add a enum named as 'brands'.

**Comment by ZYang2077** [comment]
@yorkeyao When i use the inference.py to genetate images, why the generated pictures all contain bus? How can I get pictures of other kinds of vehicle?
![image](https://user-images.githubusercontent.com/58316756/91024853-1fd11600-e62b-11ea-8f22-dced3c1c7c5d.png)

**Comment by yorkeyao** [comment]
Have you downloaded the background images? If VehicleX cannot find links for background images, this situation would happen (I will add an assert in the inference.py to check links for background images). May I ask can you generate all kinds of vehicles in the training mode? (training mode does not require background images)

**Comment by ZYang2077** [comment]
@yorkeyao Sorry i don't understand what you mean. Doesn’t the training mode only output a VehicleID-out.json file? I didn't find out introduction about the generated image in the training mode from your readme. BTW, can you provide your VehicleID-out.json, so I can compare whether the JSON file I produced is correct.

**Comment by ZYang2077** [comment]
this is my output JSON file:

{
    "name": "VehicleID training",
    "camera number": 1,
    "camera list": [
        {
            "camera id": 0,
            "target dir": "./datasets/VehicleID_V1.0/VehicleID.npz",
            "output dir": "./VID_ReID_Simulation/",
            "data size": 113346,
            "attributes": {
                "orientation": [
                    "Gaussian Mixture",
                    [
                        0,
                        360,
                        30
                    ],
                    [
                        180.0,
                        180.0,
                        180.0,
                        180.0,
                        180.0,
                        180.0
                    ],
                    [
                        20,
                        20,
                        20,
                        20,
                        20,
                        20
                    ]
                ],
                "light intensity": [
                    "Gaussian",
                    [
                        0,
                        3,
                        0.3
                    ],
                    2.6999999999999997,
                    0.63
                ],
                "light direction": [
                    "Gaussian",
                    [
                        45,
                        135,
                        15
                    ],
                    45.0,
                    7.07
                ],
                "camera height": [
                    "Gaussian",
                    [
                        4,
                        13,
                        1
                    ],
                    4.0,
                    0.4
                ],
                "camera distance": [
                    "Gaussian",
                    [
                        -2,
                        13,
                        3
                    ],
                    4.0,
                    0.6
                ]
            },
            "FD distance": 4500.392400150078
        }
    ]
}

**Comment by yorkeyao** [comment]
Sorry for the confusion. What I mean is have you download the Background images as this file structure shows here? 
![background_imgs](https://user-images.githubusercontent.com/24240658/91294719-4e8eee00-e7dd-11ea-8e66-d6de615ff502.PNG)
And any JSON file should run with inference.py fine.  
(Updated in 8/30): I have updated the inference.py with a new assert to check background images folder
