### ISSUE TITLE
The code of the Unity python interface

### ISSUE THREAD

**Issue by YuhaoCheng** [yorkeyao/VehicleX#7]
Thanks for your brilliant work. Would you mind sharing the code of the python interface? I want to know how to control Unity by using Python. Thanks. If you think uploading the codes isn't convenient, you would send me the email. Thanks a lot.

**Comment by yorkeyao** [comment]
Thank you for your question. We have released VehicleX source code include the unity python interface in https://github.com/yorkeyao/VehicleX/tree/master/Unity%20Source

**Comment by YuhaoCheng** [comment]
> Thank you for your question. We have released VehicleX source code include the unity python interface in https://github.com/yorkeyao/VehicleX/tree/master/Unity%20Source

Thanks for your answer. I have noticed this folder in your projects, while what indeed confuses me is how you just use the Python script without opening a Unity editor. I'm curious about this part. Thanks for your time.

**Comment by yorkeyao** [comment]
If your question is about the exact code in the unity source to make the connection. You may check function AgentAction in the PosAgent.cs.

**Comment by YuhaoCheng** [comment]
Thanks for your time. However, I can't find the `PosAgent.cs` in this project. Would you mind telling me where I can find this file?

**Comment by yorkeyao** [comment]
It is located in Assets/Scripts/PosAgent.cs. BTW you can always look up a file by search in the unity editor. 
![posagent](https://user-images.githubusercontent.com/24240658/92456433-420b8c00-f206-11ea-8fa4-fc5b73bd5865.PNG)

**Comment by YuhaoCheng** [comment]
OK. I will check this file and figure out whether it can help me solve this question. Thanks a lot.
