### ISSUE TITLE
Errors in Uity Editor

### ISSUE THREAD

**Issue by muaz-urwa** [yorkeyao/VehicleX#8]
When I open the project using Unity Hub I get following errors:

![Screenshot from 2020-09-09 16-31-08](https://user-images.githubusercontent.com/43106180/92593499-a25c0580-f2ba-11ea-81b6-88e3107c5c83.png)

Then I followed instructions in readme and replaced the contents of PosAgent.cs with contents of RawImage.cs. 

Then I am getting following errors:

![Screenshot from 2020-09-09 16-33-48](https://user-images.githubusercontent.com/43106180/92593657-efd87280-f2ba-11ea-832e-718b4a1d8bd5.png)

Any ideas on how to tackle these ?

**Comment by yorkeyao** [comment]
Thank you for your question. I have mentioned this error in the notice part of the readme. 

If you see error CS1061: 'RawImage' does not contain a definition for 'm_Texture'. Please open this file and replace all content with ./Script/RawImage.cs.

**Comment by yorkeyao** [comment]
Thank you for your question. Could you please click the 'Clear' button above and see how many error remain?

**Comment by muaz-urwa** [comment]
![Screenshot from 2020-09-09 18-22-29](https://user-images.githubusercontent.com/43106180/92604087-8744c200-f2c9-11ea-80d9-2edb36403fc5.png)

**Comment by yorkeyao** [comment]
It seems weird to me that you have this bug. Could you please check whether PosAgent.cs is removed here?
![Capture](https://user-images.githubusercontent.com/24240658/92609538-0520c180-f2fa-11ea-8eb9-85d263ca50f0.PNG)

**Comment by muaz-urwa** [comment]
![Screenshot from 2020-09-09 19-28-42](https://user-images.githubusercontent.com/43106180/92611952-c3c8eb80-f2d2-11ea-9fbd-3e3d7a667ecf.png)

**Comment by yorkeyao** [comment]
I think I know what is the error and sorry for not making it clear. What I mean is to replace original RawImage.cs with contents of ./Script/RawImage.cs, not to replace PosAgent.cs with the contents of ./Script/RawImage.cs. The reason for such replacement is I modified some content in RawImage.cs where it is the part of the source code of the Unity engine. So I cannot include RawImage.cs in my project directly. 

I will try some alternative ways to implement it in the future.

**Comment by muaz-urwa** [comment]
Great, that resolved the issue. Thank you so much !

I noticed that linux standalone binary is missing.

Both links on this [page](https://github.com/yorkeyao/VehicleX/tree/master/VehicleX%20Interface) point to the windows binary on google drive.

**Comment by yorkeyao** [comment]
Oh many thanks. I have updated this link.

**Comment by muaz-urwa** [comment]
Great. Thank you.

I get the same car in all images when I run inference.py using the unity editor by replacing

env = UnityEnvironment(file_name=env_name) 

with 

env = UnityEnvironment(file_name=None)

 car_id is always 0, color_id is always 4 and type_id is always 0.

**Comment by yorkeyao** [comment]
There should be some bugs. Could you please go to the console and check the error?

**Comment by muaz-urwa** [comment]
I have not downoaded the background images, so i repeatedly get this error on console:

DirectoryNotFoundException: Could not find a part of the path '/home/urwa/Documents/unsupervised/VehicleX/unity/VehicleX Unity Source/Background_imgs/vdo (37).avi'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <a8ed250850854b439cedc18931a314fe>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at <a8ed250850854b439cedc18931a314fe>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <a8ed250850854b439cedc18931a314fe>:0

Could this be the reason ?


Using Build-linux/VehicleX is also giving me one car.

**Comment by muaz-urwa** [comment]
Missing background images was the reason.

IEnumerator Example(float[] vectorAction)  function in PosAgent.cs encounters an error if background images are missing. And then rest of function does not execute.

Your inference script has an exception ensuring that BackgroundImages folder exists. I removed it, that is why I wasnt getting exception.

**Comment by yorkeyao** [comment]
Yes, the inference mode requires background images. otherwise, you can have ''python inference.py --train_mode True''

**Comment by muaz-urwa** [comment]
Now I am able to run using the linux standalone version.

But using the unity editor I get the following error.

NullReferenceException: Object reference not set to an instance of an object
PosAgent+<Example>d__24.MoveNext () (at Assets/Scripts/PosAgent.cs:215)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /home/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
PosAgent:AgentAction(Single[], String) (at Assets/Scripts/PosAgent.cs:310)
MLAgents.Agent:AgentAction(Single[], String, CustomAction) (at Assets/Resources/ML-Agents/Scripts/Agent.cs:872)
MLAgents.Agent:AgentStep() (at Assets/Resources/ML-Agents/Scripts/Agent.cs:1069)
MLAgents.Academy:EnvironmentStep() (at Assets/Resources/ML-Agents/Scripts/Academy.cs:562)
MLAgents.Academy:FixedUpdate() (at Assets/Resources/ML-Agents/Scripts/Academy.cs:583)



Errors occur when script tries to access attributes of Background_Img such as:  Background_Img.m_Texture

**Comment by muaz-urwa** [comment]
following line in start() in POsAgent.cs returns Null.

GameObject.FindGameObjectWithTag("Background_Img").GetComponent<UnityEngine.UI.RawImage>();

**Comment by yorkeyao** [comment]
I think the Unity editor is only available in windows. May I ask do you get the same error in windows system?

**Comment by muaz-urwa** [comment]
Do you mean that this repository only supports the linuxx unity editor ?

I am able to perform the inference using linux and unity editor but I get images of the same car over and over again. Because of the error I mentioned above.

Background_Img GameObject has no component of type <UnityEngine.UI.RawImage> and returns null. It doesnt lool like an OS issue.

I will try on windows too and let you know.

**Comment by yorkeyao** [comment]
I haven't test unity editor in Linux (unity editor just begin to support Linux last year when I write this code). I just rebuild my system in windows it seems works well (by replacing Unity/Hub/Editor/2019.3.0a8/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Rawimages.cs with ./Script/RawImage.cs). 

May I ask is this an error during running? it seems there is still something wrong with the RawImage.cs

**Comment by muaz-urwa** [comment]
Ah thank you so much !

I was copying the rawimage in to the wrong place assets/scripts

It is working like a charm now !

I you can put the path "Unity/Hub/Editor/2019.3.0a8/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Rawimages.cs" in the readme instructions it would be very easy for newbies to Unity.

Thanks again !

**Comment by yorkeyao** [comment]
Great! I have updated the readme.

**Comment by yorkeyao** [comment]
Cool! I have updated the readme.
